Enhancement gcp disks
yugabyte/cloud-resource-cleanup pull request #13
Opened 2023-04-25 14:55 UTC by saratkumar-yb

2023-05-31 18:19 UTC, mbautin commented
The PR needs to have a better title and description.

2023-05-31 18:23 UTC, mbautin requested changes

2023-05-31 18:23 UTC, mbautin commented on crc.py
> +        self, resource: str, operation_type: str, operated_list: object
Use `Any` instead of `object`.
If it could be multiple different types, use `Union`, etc.

2023-05-31 18:23 UTC, mbautin commented on crc.py
> +                #member_id = self.slack_lookup_user_by_email(f"{key}@yugabyte.com")
Remove commented-out code.

2023-05-31 18:23 UTC, mbautin commented on crc.py
> +        slack_notify_users,
Specify type for this parameter.

2023-05-31 18:23 UTC, mbautin commented on crc.py
> +                "Incorrect Cloud Provided. Disks operation is supported only on AZURE, GCP. AWS, GCP clean the NICs, Disks along with VM"
This is confusing. GCP is now mentioned twice in two sentences that were previously referring to mutually exclusive situations.

2023-05-31 19:08 UTC, mbautin requested changes

2023-06-14 05:39 UTC, zlareb1-yb requested changes

2023-06-14 05:39 UTC, zlareb1-yb commented on crc.py
> +        help="The the gcp label that can be used to get username. Example: --slack_user_label yb_owner",
replace yb_owner with something like owner. This may leak sensitive tag information which we use in opensource

2023-06-14 05:39 UTC, zlareb1-yb commented on crc.py
> +    def slack_lookup_user_by_email(self, email):
add docstring

2023-06-14 05:39 UTC, zlareb1-yb commented on crc.py
> +    def get_user_groups_list(self):
add docstring

2023-06-14 05:39 UTC, zlareb1-yb commented on crc.py
>          :param age: Dictionary of age conditions to filter the disks.
add added param information

2023-06-14 05:39 UTC, zlareb1-yb commented on crc.py
> +                "Incorrect Cloud Provided. Disks operation is supported only on AZURE, and GCP. AWS clean the NICs, Disks along with VM"
Correct statement --> Incorrect Cloud Provided. Disks operation is supported only on AZURE and GCP. AWS cleans the NICs, Disks along with VM

2023-06-14 05:39 UTC, zlareb1-yb commented on crc.py
> +    if slack_notify_users and slack_user_label == None:
change this to --> if slack_notify_users and not slack_user_label:

2023-06-14 05:39 UTC, zlareb1-yb commented on crc/gcp/disk.py
> +    def _is_old_disk_detach(self, disk):
change method name to --> _is_disk_older_than_detach_age

2023-06-14 05:39 UTC, zlareb1-yb commented on crc/gcp/disk.py
> +                )
add new line

2023-06-14 05:39 UTC, zlareb1-yb commented on crc/gcp/disk.py
> +                logging.info(
both can be logging.warning

2023-06-14 05:39 UTC, zlareb1-yb commented on crc/utils.py
>      fh.setLevel(logging.INFO)
checkout the crc.log file

2023-06-14 05:45 UTC, saratkumar-yb commented on crc/gcp/disk.py
> +        age: int,
will take rename as an improvement

2023-06-14 05:45 UTC, saratkumar-yb commented on crc/gcp/disk.py
> +        :param notags: dictionary containing key-value pairs as filter tags to exclude disks which do not have these tags
will take rename as a seprate improvement

2023-06-14 05:45 UTC, saratkumar-yb commented on crc/gcp/disk.py
> +        exception_regex: List[str],
will take rename as a seprate improvement

2023-06-14 05:45 UTC, zlareb1-yb commented on crc/gcp/disk.py
> +        age: int,
what about Azure when these params are not passed? like detach_age

2023-06-14 06:00 UTC, zlareb1-yb commented
Add GitHub README changes as well

2023-06-14 06:22 UTC, saratkumar-yb commented on crc/gcp/disk.py
> +        age: int,
This should not effect Azure as detach_age param is optional. Will update README that currently we support only for GCP disks.

2023-06-14 06:24 UTC, saratkumar-yb commented on crc/utils.py
>      fh.setLevel(logging.INFO)
I have removed crc.log file from repo and creating the directory and file during run.

2023-06-14 14:34 UTC, saratkumar-yb commented on crc/gcp/disk.py
> +        age: int,
Tried a sample dry run of azure, works fine.

2023-06-14 14:37 UTC, zlareb1-yb approved these changes

2023-06-14 16:28 UTC, zlareb1-yb commented on README.md
>  3. To delete all GCP disks that are older than 2 days and have the tag `test_task` with the value `stress-test` and project_id as 'test_project':
make this 14 days instead of 2 days

2023-06-14 16:28 UTC, zlareb1-yb commented on crc.py
> +            disk.delete()
disk.delete() can be outside if else as it is common to both AZU, GCP

2023-06-15 05:23 UTC, saratkumar-yb commented on README.md
>  3. To delete all GCP disks that are older than 2 days and have the tag `test_task` with the value `stress-test` and project_id as 'test_project':
done

2023-06-15 05:23 UTC, saratkumar-yb commented on crc.py
> +            disk.delete()
done

2023-06-15 06:07 UTC, merged