KMS deletion for AWS
yugabyte/cloud-resource-cleanup pull request #16
Opened 2023-11-21 04:18 UTC by Shanu-Rajmaniar-yb

2023-11-29 05:08 UTC, zlareb1-yb commented on crc/aws/kms.py
> +    jenkins_user = 'arn:aws:iam::454529406029:user/jenkins-slave'
this should come as CLI argument

2023-11-29 21:28 UTC, Shanu-Rajmaniar-yb commented on crc/aws/kms.py
> +        :type filter_tags: Dict[str, List[str]]
Done

2023-11-29 21:28 UTC, Shanu-Rajmaniar-yb commented on crc/aws/kms.py
> +import logging
Done

2023-11-29 21:29 UTC, Shanu-Rajmaniar-yb commented on crc/aws/kms.py
> +                        and "Yugabyte Master Key" in key_des
Done, created new arg to be parsed from CLI that should match key description in JSON policy.

2023-11-29 21:30 UTC, Shanu-Rajmaniar-yb commented on crc/aws/kms.py
> +                    print(f"KEY SKIPPED")
Done, removed print statements and added logging support everywhere. Also added keyname which is being skipped.

2023-11-29 21:31 UTC, Shanu-Rajmaniar-yb commented on crc/aws/kms.py
> +                    client.schedule_key_deletion(KeyId=cmk_id, PendingWindowInDays=14) # Decide for appropriate window
Done, set the minimum duration to 7 days as default. User can override this by passing from CLI too.

2023-11-29 21:32 UTC, Shanu-Rajmaniar-yb commented on crc/aws/kms.py
> +            )
Done

2023-11-29 21:32 UTC, Shanu-Rajmaniar-yb commented on crc/aws/kms.py
> +    jenkins_user = 'arn:aws:iam::454529406029:user/jenkins-slave'
Done

2023-11-30 08:32 UTC, zlareb1-yb requested changes

2023-11-30 08:32 UTC, zlareb1-yb commented on crc/aws/kms.py
> +            a = 0
remove this

2023-11-30 08:32 UTC, zlareb1-yb commented on crc.py
> +# KMS = "KMS"
why is this commented

2023-11-30 08:32 UTC, zlareb1-yb commented on crc.py
> +        "--pending_window",
this name is not making sense. It shd be something like `kms_pending_window`

2023-11-30 08:32 UTC, zlareb1-yb commented on crc.py
> +        "--key_description",
it should be `kms_key_description`

2023-11-30 08:32 UTC, zlareb1-yb commented on crc.py
> +        "--user",
it shd be jenkins_user and we shd not be using "`-u`" type bcz it is not explanatory

2023-11-30 08:32 UTC, zlareb1-yb commented on crc.py
> +        "-k",
remove -k

2023-11-30 08:32 UTC, zlareb1-yb commented on crc.py
> +        "-pw",
remove -pw

2023-11-30 08:32 UTC, zlareb1-yb commented on crc.py
> +    # Add Argument for Pending Window
add README for these new arguments

2023-11-30 08:32 UTC, zlareb1-yb commented on crc/aws/kms.py
> +            logging.warning("Tags and not present")
*Exception tags are not present

2023-11-30 08:32 UTC, zlareb1-yb commented on crc/aws/kms.py
> +                    not self.exception_tags[k] or v in self.exception_tags[k]
what is meaning of not self.exception_tags[k]? in which case this may occur?

2023-11-30 08:32 UTC, zlareb1-yb commented on crc/aws/kms.py
> +                logging.warning(f"KEY SKIPPED", keys["KeyId"])
is this correct syntax?

2023-11-30 08:32 UTC, zlareb1-yb commented on crc/aws/kms.py
> +        # Add deleted IPs to deleted_ips list
fix this msg

2023-12-06 03:52 UTC, Shanu-Rajmaniar-yb commented on crc/aws/kms.py
> +            a = 0
Done

2023-12-06 03:53 UTC, Shanu-Rajmaniar-yb commented on crc.py
> +        "--pending_window",
yes changed

2023-12-06 06:16 UTC, Shanu-Rajmaniar-yb commented on crc/aws/kms.py
> +                logging.warning(f"KEY SKIPPED", keys["KeyId"])
Corrected

2023-12-06 06:45 UTC, Shanu-Rajmaniar-yb commented on crc/aws/kms.py
> +                    not self.exception_tags[k] or v in self.exception_tags[k]
If tag key is present but value is null/falsy.

2023-12-06 06:47 UTC, Shanu-Rajmaniar-yb commented on crc.py
> +# KMS = "KMS"
Missed it, uncommented

2023-12-06 06:48 UTC, Shanu-Rajmaniar-yb commented on crc.py
> +    # Add Argument for Pending Window
Done

2023-12-06 06:57 UTC, zlareb1-yb requested changes

2023-12-06 06:57 UTC, zlareb1-yb commented on README.md
> +* `jenkins_user`: Use this option to specify the jenkins slave AWS ARN for which keys will be deleted.
change this to user instead of jenkins_user

2023-12-06 08:19 UTC, Shanu-Rajmaniar-yb commented on README.md
> +* `jenkins_user`: Use this option to specify the jenkins slave AWS ARN for which keys will be deleted.
Done, changed to kms_user

2023-12-06 09:25 UTC, zlareb1-yb commented on README.md
> +* `kms_user`: Use this option to specify the jenkins slave AWS ARN for which keys will be deleted.
Dont mention Jenkins here

2023-12-06 09:25 UTC, zlareb1-yb commented on README.md
> +* `kms_user`: Use this option to specify the jenkins slave AWS ARN for which keys will be deleted.
Also add one example to delete KMS in examples section

2023-12-06 09:38 UTC, merged